#!/usr/bin/env bash
set -euo pipefail

# Use ekalinin/github-markdown-toc to refresh the README TOC.
# This script fetches the upstream helper on demand (requires network) and
# exits non-zero only when it actually changes the README (so pre-commit
# fails only when updates are applied).

TARGET_FILE="${1:-README.md}"

tmp_script="$(mktemp)"
tmp_original="$(mktemp)"
trap 'rm -f "$tmp_script" "$tmp_original"' EXIT

cp "$TARGET_FILE" "$tmp_original"

curl -fsSL https://raw.githubusercontent.com/ekalinin/github-markdown-toc/master/gh-md-toc > "$tmp_script"
chmod +x "$tmp_script"

"$tmp_script" --no-backup "$TARGET_FILE"

# Drop author/date metadata comments the tool inserts.
perl -0pi -e 's/<!-- Added by: .*? -->\n?//g; s/<!-- Auto generated by https:\/\/github.com\/ekalinin\/github-markdown-toc -->\n?//g' "$TARGET_FILE"

if cmp -s "$tmp_original" "$TARGET_FILE"; then
  exit 0
else
  exit 1
fi
