#!/usr/bin/env bash
set -euo pipefail

# Refresh README TOC using ekalinin/github-markdown-toc.
# Exits non-zero only when it actually changes the file.

TARGET_FILE="${1:-README.md}"

tmp_script="$(mktemp)"
tmp_original="$(mktemp)"
trap 'rm -f "$tmp_script" "$tmp_original"' EXIT

cp "$TARGET_FILE" "$tmp_original"

curl -fsSL https://raw.githubusercontent.com/ekalinin/github-markdown-toc/master/gh-md-toc > "$tmp_script"
chmod +x "$tmp_script"

"$tmp_script" --no-backup "$TARGET_FILE"

# Drop metadata comments the tool inserts.
sed -i '' -e '/<!-- Added by: /d' \
  -e '\|<!-- Auto generated by https://github.com/ekalinin/github-markdown-toc -->|d' \
  -e '\|<!-- Created by https://github.com/ekalinin/github-markdown-toc -->|d' "$TARGET_FILE"

if cmp -s "$tmp_original" "$TARGET_FILE"; then
  exit 0
else
  exit 1
fi
